GTNewHorizons/lwjgl3ify

- src/main/java/me/eigenraven/lwjgl3ify/mixins/game/MixinStitcher.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/game/MixinTextureAtlasSprite.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/game/MixinTextureMap.java
- src/main/java/me/eigenraven/lwjgl3ify/textures/FastByteChannel.java
- src/main/java/me/eigenraven/lwjgl3ify/textures/NativeBackedImage.java
- src/main/java/me/eigenraven/lwjgl3ify/textures/StbStitcher.java
- src/main/resources/mixins.lwjgl3ify.json
This PR improves the performance of Minecraft's texture parsing and stitching by replacing various algorithms with LWJGL3's STB bindings. The changes include using stb_image to parse images at a rate significantly faster than Java's ImageIO, and using stb_rect_pack to stitch images significantly faster.
This PR builds mostly off of the `NativeImage` construct in modern Minecraft versions, adapting it to work with 1.7.10 by extending BufferedImage. This allows easy compatibility with the existing code, as the implementation details of the image storage can be hidden.
When reloading resource packs (by adding uu-tex, gtnh 32x, and gtnh faithful), the time it takes for the game to un-freeze goes from 8.3 seconds without this patch to 4.8 seconds with this patch. That's roughly a 70% …
> Improve performance of texture loading and stitching by using STB

- src/generated/java/org/lwjglx/opengl/GL11.java
glColor3ub is causing SEGFAULT on negative values on macOS, use glColor3i instead.
See https://github.com/LWJGL/lwjgl3/issues/858
This call is rarely used so performance impact should be minimal.
> HACK: Temporary workaround for glColor3ub crash on macOS

- src/generated/java/org/lwjglx/opengl/GL11.java
See #17
Found out that Botania is using 4ub variant, we need to patch it too.
> HACK: Apply the same workaround for glColor4ub

- src/generated/java/org/lwjglx/opengl/GL11.java
It's not needed for LWJGL version 3.3.2-20230304.162250-10 and up.
> Revert the glColor3ub hack

- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/org/lwjglx/input/EventQueue.java
- src/main/java/org/lwjglx/input/Keyboard.java
This should provide some very basic IME support for multibyte inputs with much less hacks than the other method. I'm keeping the other method in as it can provide a better experience with AWT integration.
> Add multibyte char event handling by duplicating key events when multiple chars happen after a single keypress

- addon.gradle
- build.gradle
- dependencies.gradle
- java9args.txt
- prism-libraries/mmc-pack.json
- prism-libraries/patches/me.eigenraven.lwjgl3ify.forgepatches.json
- prism-libraries/patches/org.lwjgl3.json
Update from lwjgl 3.3.2 snapshots to the stable release - currently from upstream builds host because it's not been put in Mojang's repositories yet.
> LWJGL 3.3.2 stable update

- src/main/java/org/lwjglx/opengl/Display.java
Closes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14421
I don't think the ALT check is actually needed for anything, it was used earlier for a discarded IME switching mechanism.
> Synthesize ASCII escape codes for ctrl+alt+CHAR inputs too

- prism-libraries/patches/org.lwjgl3.json
Now that mojang published vanilla 1.20.2 we can use the upstream JSON for lwjgl 3.3.2: <https://github.com/PrismLauncher/meta-launcher/blob/master/org.lwjgl3/3.3.2.json>
> Update to mojang's lwjgl 3.3.2 distribution to match vanilla 1.20.2

- README.MD
- addon.gradle
- addon.late.gradle
- dependencies.gradle
- prism-libraries/patches/net.minecraft.json
- prism-libraries/patches/net.minecraftforge.json
- src/forgePatches/java/cpw/mods/fml/common/asm/transformers/TerminalTransformer.java
- src/main/java/me/eigenraven/lwjgl3ify/core/Lwjgl3ifyCoremod.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/fml/ModVisitorAsmVersion.java
- Modify all version-restricted ASM transformers inside of forge/FML to accept Java 21 classes, this means mods *can* be compiled with Java 21 if no backwards compatible is desired by someone or for experiments (3rd party coremods can still break)
- Update ASM to 9.5 for Java 21 support inside of forge and FML
- Embed all modified libraries in the forgePatches jar to remove the annoying installation step of merging client libraries into the server installation directory (also simplifies launchwrapper updates, DAXXL no longer needs updating with new library files)
- Update and clarify some minor issues in the README
Tested manually in the dev env, a Prism client instance and a fresh forge server instance - the server installation process is much less error-prone now!
> Installation simplification and ASM upgrade

- src/main/java/org/lwjglx/input/Keyboard.java
Avoids the following error when running in debug mode:
```
Description : Invalid key -1
Stacktrace  :
org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43)
org.lwjgl.system.JNI.invokePI(Native Method)
org.lwjgl.glfw.GLFW.glfwGetKey(GLFW.java:3746)
org.lwjglx.debug.$Proxy$4840.glfwGetKey577(Unknown Source)
org.lwjglx.input.Keyboard.isKeyDown(Keyboard.java:263)
net.minecraft.client.settings.KeyBinding.hodgepodge$updateKeyStates(KeyBinding.java:590)
net.minecraft.client.Minecraft.handler$zeb000$hodgepodge$updateKeysStates(Minecraft.java:6596)
net.minecraft.client.Minecraft.setIngameFocus(Minecraft.java:1386)
net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:871)
net.minecraft.client.gui.GuiChat.keyTyped(GuiChat.java:119)
```
> Check for GLFW_KEY_UNKNOWN

- src/main/java/org/lwjglx/opengl/ContextCapabilities.java
When running on OSX `OpenGL45` is false, so it checks the next one `GL_ARB_direct_state_access` which was causing an error
> Add missing GL_ARB_direct_state_access needed for osx

- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/org/lwjglx/opengl/Display.java
This PR accounts for horizontal scrolling (as opposed to the traditional vertical scrolling), i.e. when holding SHIFT on macOS, to be accounted for by the game by passing `xoffset` (horizontal scroll offset) instead of `yoffset` (vertical scroll offset) to `Mouse#addWheelEvent` when `yoffset` is `0` (and thus not vertical) when initializing `Display$Window#mouseButtonCallback`.
This was a bug in Minecraft ever since it updated to LWJGL 3 officially, until it was fixed in 1.20.2.  
Note that the vanilla game (now) *inverts* horizontal scrolling by default - for example, in my case (on my macOS machine), when scrolling through items in the hotbar, scrolling normally would move the item selector(?) in one direction, while doing so while holding SHIFT would move it in the other.
This does not …
> Fix for horizontal scrolling

- launcher-metadata/version.json
You can find a diff to the [`1.7.10.json`](https://piston-meta.mojang.com/v1/packages/ed5d8789ed29872ea2ef1c348302b0c55e3f3468/1.7.10.json) [here](https://www.diffchecker.com/zkm81UwG/).
1. Modify `bin/modpack.jar`: In it, there is already a `version.json` file - replace it with this file.
2. Set the required Java version to a version higher than 1.8. This can be done per modpack version when using Technic Solder, so simply shipping a version twice (1.8 and >1.8) is possible and easy to do.
3. Done!
> Add `version.json` for use in e.g. Technic Launcher

- build.gradle
- dependencies.gradle
- src/main/java/me/eigenraven/lwjgl3ify/core/Lwjgl3ifyCoremod.java
- src/main/java/me/eigenraven/lwjgl3ify/core/LwjglRedirectTransformer.java
Allows coremods to be more flexible with asm transforms
> Remove the need for lwjgl package transformer exclusions

- build.gradle
- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/org/lwjglx/opengl/Display.java
> Fix handling of Ctrl+Alt vs AltGr on Windows

- src/forgePatches/java/net/minecraftforge/common/util/EnumHelper.java
Adds Enum Map to keep track of all Enum Names associated with their Enum Classes
- $1, $2, $3, $4.... and so on will be appended to the Enum Name until the Duplication clause is satisfied.
The issue in detail is explained here: #115 
_The enum names are case-insensitive when they are registered so all enums capitalized before comparison_
> Fixes Enum Duplication Issue

- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/org/lwjglx/openal/AL.java
Two toggles are now turned off by default to disable HRTF
Fixed the config to lowercase else it will appear in the config like this:
```
openglContext {
}
openglcontext {
B:debugContext=false
B:doubleBuffer=true
B:noError=false
B:srgb=false
}
```
> Add Config Toggle to Enable / Disable HRTF Bools in OpenAl

- src/main/java/me/eigenraven/lwjgl3ify/rfb/EarlyConfig.java
> Add more default LOTR mod ExtensibleEnums

- src/main/java/org/lwjglx/opengl/Display.java
updateRawMouseMode should only be called after displayCreated has been set to true, otherwise raw mouse mode will never be enabled when (re-)starting the game.
> Moved updateRawMouseMode to be called after displayCreated=true

- src/main/java/org/lwjglx/Sys.java
The Sys.getClipboard() method must be static
Original source: https://github.com/LWJGL/lwjgl/blob/master/src/java/org/lwjgl/Sys.java#L269
> Make Sys.getClipboard() static.

- src/main/java/me/eigenraven/lwjgl3ify/Lwjgl3ifyLateMixins.java
- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/me/eigenraven/lwjgl3ify/core/Lwjgl3ifyCoremod.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/Mixins.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/TargetedMod.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/fml/ItemStackHolderRef.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/fml/JarDiscoverer.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/fml/ObjectHolderRef.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/fml/ObjectHolderRegistry.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/game/MixinBorderlessWindow.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/game/MixinMinecraftKeyBinding.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/game/MixinStitcher.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/game/MixinTextureAtlasSprite.java
- src/main/java/me/eigenraven/lwjgl3ify/mixins/early/game/MixinTextureMap.java
- src/main/resources/mixins.lwjgl3ify.late.json
Pull in the mixin framework from Hodgepodge and port everything over
> Better mixin infrastructure

- src/main/java/org/lwjglx/input/Mouse.java
- src/main/java/org/lwjglx/opengl/Display.java
The game expects `getWidth` and `getHeight` to return framebuffer coordinates rather than screen-space coordinates (as shown by the calls to `glViewport`). This was broken on scaling factors greater than 1 but also masked by `GL_SCALE_FRAMEBUFFER`.
Additionally, the game's mouse code *also* expects framebuffer coordinates to be returned. This fixes that by converting to and from screen-space during calls to mouse code.
Disable `GLFW_COCOA_RETINA_FRAMEBUFFER` for now, it seems to not play nice on non-MacOS systems. At least for me it makes the title screen much larger than the window when playing in fullscreen.
Screenshot before the change:
Screenshot after the change:
Before is marginally fuzzier (and obviously doesn't work with the title screen)
> Fix scaling on HiDPI screens with Wayland

- src/main/java/org/lwjglx/openal/AL.java
Supersedes GTNewHorizons/Hodgepodge#420 as a fix for the SoundManager NPE crashes
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17190
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17190
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16281
Fixes https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12848
Fixes https://github.com/GTNewHorizons/Hodgepodge/issues/406
Adds null check that is present in LWJGL2 when initializing OpenAL sound.
> Fix SoundManager handling when no sound devices exist

- dependencies.gradle
- prism-libraries/patches/net.minecraft.json
Tested in a modified nightly 559. Unimixins has been bumped, but I'm unsure where in the buildscript Unimixins is pulled in
> Bump ASM to support Java 24

- src/main/java/org/lwjglx/openal/AL.java
- src/main/java/org/lwjglx/opengl/Display.java
- src/main/java/org/lwjglx/opengl/GL15x.java
- src/main/java/org/lwjglx/opengl/GL20x.java
- src/main/java/org/lwjglx/util/glu/MipMap.java
Replace some buffer allocations with MemoryStack instead. All replacement locations should be contained - I avoided touching methods which returned buffers, as those likely can't be reclaimed once the method exits.
> Reduce buffer allocations

- launcher-metadata/version.json
Java 21 is currently the newest Java version used by vanilla MC (see https://piston-meta.mojang.com/v1/packages/a3bcba436caa849622fd7e1e5b89489ed6c9ac63/1.21.4.json). This PR updates the `version.json` file to reflect this, so launchers that use this file can use the correct JRE.
> Update `version.json` Java version to 21

- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
- src/main/java/me/eigenraven/lwjgl3ify/core/Config.java
- src/main/java/org/lwjglx/opengl/Display.java
Thanks to this mod, its possible to run minecraft natively on Wayland, however it does not set the `app_id`, the identifier for windows spawned by an application. Setting this allows Wayland compositors to apply rules to windows (in my case I wanted minecraft to always be floating, not tiled).
This PR simply sets the Wayland app_id via GLFW. The window hint is ignored by other platforms, same as for the X11 and Cocoa hints.
Output from `swaymsg -t get_tree` (which shows information about the current windows)
**Before** (minecraft has no app_id, but prism does):
```
#6: workspace "1"
#31: con "Prism Launcher 9.1" (xdg_shell, pid: 172749, app_id: "org.prismlauncher.PrismLauncher")
#32: con "Console window for GT_New_Horizons_2.7.1_Java_17-21 — Prism Launcher 9.1" (xdg_shell, pid: 172749, …
```
> Set wayland app_id

- src/main/java/me/eigenraven/lwjgl3ify/rfb/EarlyConfig.java
Fixes:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18853
```
java.lang.RuntimeException: Enum buildcraft.api.transport.IPipeTile$PipeType was not made extensible, add it to lwjgl3ify configs.
[20:04:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//me.eigenraven.lwjgl3ify.EnumHelper.addEnum(EnumHelper.java:141)
[20:04:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java)
[20:04:51] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//logisticspipes.proxy.buildcraft.BuildCraftProxy.getLPPipeType(BuildCraftProxy.java:282)
[20:04:51] [Server thread/INFO] …
```
> Fix LogisticsPipes BCCompat with Lwjgl3ify

- src/main/java/me/eigenraven/lwjgl3ify/rfb/EarlyConfig.java
There were 3 reports of this issue in the #help channel. This can happen when the server runs out of space and a zero-length `lwjgl3ify-early.json` is left behind.
```java
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
at ...
Caused by: java.lang.NullPointerException: Cannot read field "extensibleEnums" because "cfg" is null
at System//me.eigenraven.lwjgl3ify.rfb.EarlyConfig.load(EarlyConfig.java:100)
at System//me.eigenraven.lwjgl3ify.rfb.Lwjgl3ifyRfbPlugin.onConstruction(Lwjgl3ifyRfbPlugin.java:37)
at com.gtnewhorizons.retrofuturabootstrap.plugin.PluginLoader.initializePlugins(PluginLoader.java:112)
at System//net.minecraft.launchwrapper.Launch.rfb$realLaunch(Launch.java:197)
at System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35) …
```
> Fix loading corrupted lwjgl3ify-early.json

- prism-libraries/patches/net.minecraft.json
- Java 11 is so old we shouldn't recommend it anymore
- Javas 19, 20, 22 are short term support versions that are no longer officially supported
This doesn't remove the actual code support for them, but will throw up a launcher warning about unsupported versions when trying to use them (easily bypassed if needed for testing)
> Remove unsupported jvm versions from the prism launcher manifest

- launcher-metadata/version.json
I'm currently trying to use lwjgl3ify on official launcher on macOS (without relauncher), but it hangs inside `glfwInit()` invocation. In contrast relauncher works perfectly fine.
The culprit seems to be `-XstartOnFirstThread` JVM argument. Removing this starts the game completely normal. I guess `glfw_async` is not compatible with `-XstartOnFirstThread`.
Relauncher is not affected by this problem, as it ignores `jvm` of `version.json`.
- macOS 10.13.6, x86_64
- macOS 15.1.1, arm64
- https://github.com/LWJGL/lwjgl3/issues/767
> Remove -XstartOnFirstThread in version.json for macOS
